aes:
  # AES key used to encrypt the private RSA key
  raw_key: !!binary "dkNhVCRwUjI="
  default_iv: !!binary "AAECAwQFBgcICQoLDA0ODw=="
  # salt used in AES encryption
  salt: !!binary "ZGVmZ2hpams=" 

# server's RSA private key in PEM format, encrypted with AES, represented in base64.
priv_key: !!binary "TqTkpz5p2oBX5Uhu2WjHsySMok0aaJLWoRpY+2AhtxFovX6CzmHzSc9X76bWw4gYpYr2HMCYzB7/KOwbQ0We8lrf5WTSk8S093OAy9MLsMjVP2vqkk3apymMVlREBC9saqnLNMFD1QSzSI9zIPJLGrUL1zEiWeSUjkdU1hvA66f51ELLhcIozOc+yuRuKrxPC9+wwKIBwzV2PhpT2RAsIwPy3L/8mhs7LhNGpfZNT8NvK2cvP62yz6lC1FM2p7XjcYcteLT/ipLWaiCLlwh66gghCsSpCGM3h4SemQo85FtgOwR7NUotUYJ//34H4YrQq9BhjYHfBteCZSnFEO81DWr2sShGJxqCASXkNexs5r5eSUTm8kIfhfGasxH5Wq3qTc48cJaQ+enajKLgBx7EEQfzS4temhFPQ9Xcpxt2yTcLqfoezMCinvHY5lQrLHk02hru1k4WO9bVJH5Z7QNSDwQDLB/BCoQMd80CJ9q+JWNdxQq+IMyGAb9Y0YZY+xDtdfCkGKryGc4lUSZYQryplLO5c3opwudJ4Qq/HuATkYIsKOFanq2P0nQjnzv+FUSXe6McBGH1E7f0E3Dfj9OKArev4nByGYEcINgBTKwa60fPZcUwY+fYLZX7sSCVTFzZaO8eqQ0iQ6CFUNi6y9+doA2zVw1mZ7dafwt1gYNq2DqDgz3a2PvgRy2TvJOyHhugyEJzuomIXp59REL4ukhut10Pa7psVwQtMc1cagKOKQbrxVG2LAVPyqMczT0TFHooxWl1DyODFh6ppfdeaGjNHEZVLGfJcahqRs9JGpEvFehim3/umfaCgrtVP08QTVHKiwScpRVk6hwSJendGpSXUfSzWkFS7kUHLqsJu0hc+h6oQXajzW5unNWnkbJJ8zA/5lSDPsbk08eCH9WHWFoy+vNAo3LTFuWgDVDtcwCBmodkmBcny2ioG9+C+akEAOPGYPTeumgwJjp9b9O8nyDwTt0oM51ywLcs9sSOz7MVcljnxh/jV63KrBNHut+PF3ktkAftLyZOgJzMABcEwcVfmcTtcAJvlKAu9N344LHFr7wbQgimdCia1B7GUx9DU4r1z/SGhSnq1xwEqDujNDJlEx4HL3pLQzyzVLm0teBdFrv5T+icW8rNjVDdqaUFhj5tZWZ190NcSYpJlmj9Yr6yTVHa6L6trrZ5Ehijq9IbhqXJwcTJ4yGbS75Z/qlgBztAqCq9awazQcAqZYt+FR+DMyhd6A0PdG+9RGhtXxZhEGQJCvt08nKA9CNJHsWIorwYf4Umv8awHIrOlaMnjyzxYGPD3Z4Xz0s5NTOEOgjLmf6JjoRU/iq66jKwZ7eA8Oo3FbF3koENbXL6WzyOH2Qmbo+9pBkoxAAYtJ0JoaHDZKVrbcUfIzapqSKqSIr+J/FUQtjq6pUnP5W4f9am8dQuvMHPQ/h8pMhM/hJdkHEaL/i4vQe7kDNEgT/KOEKQYW8A+mVm2AIgQI7ODdMVcemO9WVCoMkl9/G9KrY/3iBuYVurFW+mIlu++TBziH/3XifKbsjvzPM1u+K9qfS3flz7hgd+WzkCwefgy0k8YKajO28edS5c3q2NnMbEGMaflTsopoBeG5goMZULNXo+Lt/vV+SA2jB6BRmo68YT8xVccu4Vr+VRzrUiOkeGyGTE2LFSk039dMp0EbSXh+9hN6j8ybNRz9FEfbZicwzGQ8Y3BQ5CLK2C6zyX84Pfe4wBzNvvtaHav2dEA8OTJYuPa7Si8gXmLI4xZfqbTaJT7SeyZCWNTpLo3UETbzmVCZhbXbrBih/w3ke27UwlNNsuYTfOS6pBKeeBOhOryhXXZA5M+HgMM9bHR5UybrQ9IJT/zXfFClglg5MLb0zv4xVWFr+3mko+coO8FuJT2IpDlX/OZULR8X0DDvRmdPu/iz+yrFahMmruNfuof6y73Jjc9ZyE0hy0/e1KKBEA4gVnJsjfqnLBoXFrwrXLwxUrRZUbCbunPdehkxxzfuBZ6y9pFea76tPjkYxaQK+7UaQSqAsituPSf4W4rM+ozDWSaH4kXxyn2OCCPkQ3RYQ3GmW7xmKziSFd54GP6Y/jlxlSBISABgbiu+pSGZFQzmgm54sMzFcXnlBvX2mdkacYlt6lIk6DYdEyr3BzHMIAbFgsGtGjJ/+q9j60GvIbq6ln3T2RTk7C5H9GHL9oESiS3QZEXsef2yMUCdQ3ls9A+Cb2G1K4yFq0I0JJNTRTgRywJ6FBp3naAvjbnwBnjgs6Szherr08l59JYOP/tIKGIyr/dpZQo/o="

# prefix added in front of all signatures
sig_prefix: !!binary "UkIAAQ=="


yandex:
  disk:
    oauth_token: <SET ME>
    target_dir: <SET ME>
  cloud:
    aws_access_key_id: <SET ME>
    aws_secret_access_key: <SET ME>
    bucket:
      document: <SET ME>
      metadata: <SET ME>