aes:
  # AES key used to encrypt the private RSA key
  raw_key: <SET ME>
  default_iv:  <SET ME>
  # salt used in AES encryption
  salt:  <SET ME> 

# server's RSA private key in PEM format, encrypted with AES, represented in base64.
priv_key:  <SET ME>

# prefix added in front of all signatures
sig_prefix:  <SET ME>

yandex:
  disk:
    oauth_token: <SET ME>
    target_dir: <SET ME>
  cloud:
    aws_access_key_id: <SET ME>
    aws_secret_access_key: <SET ME>
    bucket:
      document: <SET ME>
      metadata: <SET ME>